Advertising = read.csv("/Users/Simon/Desktop/stat159-hw3/data/Advertising.csv")

sink(file ="./data/eda-output.txt")
cat("TV Summary")
cat("\n")
summary(Advertising$TV)
cat("\n")
cat("Radio Summary")
cat("\n")
summary(Advertising$Radio)
cat("\n")
cat("Newspaper Summary")
cat("\n")
summary(Advertising$Newspaper)
cat("\n")
cat("Sales Summary")
cat("\n")
summary(Advertising$Sales)
cat("\n")
cat("Correlation Matrix")
cat("\n")
cor(Advertising)
sink()

correlation_matrix = cor(Advertising)

save(correlation_matrix,
     file = "./data/correlation-matrix.RData")

jpeg("./images/histogram-tv.png")
hist(Advertising$TV, main = "TV Advertising Histogram", xlab = "Money Spent on TV Advertising (in thousands)", ylab = "Number of Markets")
dev.off()
jpeg("./images/histogram-radio.png")
hist(Advertising$Radio, main = "Radio Advertising Histogram", xlab = "Money Spent on Radio Advertising (in thousands)", ylab = "Number of Markets")
dev.off()
jpeg("./images/histogram-newspaper.png")
hist(Advertising$Newspaper, main = "Newspaper Advertising Histogram", xlab = "Money Spent on Newspaper Advertising (in thousands)", ylab = "Number of Markets")
dev.off()
jpeg("./images/histogram-sales.png")
hist(Advertising$Sales, main = "Sales Histogram", xlab = "Money Spent on TV Advertising (in thousands)", ylab = "Number of Markets")
dev.off()
jpeg("./images/scatterplot-matrix.png")
pairs(Advertising)
dev.off()
